-- Generated by scripts/generate-roster-sql.ts. Do not edit by hand.
-- Source: data/roster.tsv (92 rows / 68 players)
-- Paste this into Neon's SQL editor and run as a single transaction.

BEGIN;

-- 1. Apply 0002 migration: drop Character.name unique index.
DROP INDEX IF EXISTS "Character_name_key";

-- 2. Record the migration in _prisma_migrations so future deploys skip it.
INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count)
VALUES (gen_random_uuid()::text, '1ceadb9c0d76aae680ed77bd0eae80bdfcfaeba97b87c9d000f324d15cf883b4', NOW(), '0002_drop_character_name_unique', NULL, NULL, NOW(), 1)
ON CONFLICT DO NOTHING;

-- 3. Wipe existing roster data (FK-safe order).
DELETE FROM "LootAward";
DELETE FROM "Attendance";
DELETE FROM "RosterMember";
DELETE FROM "RaidNight";
DELETE FROM "Roster";
DELETE FROM "Character";
DELETE FROM "Player";

-- 4. Recreate the singleton "Master Roster".
INSERT INTO "Roster" (name, description) VALUES ('Master Roster', 'The guild roster — every active raider''s character lives here.');

-- 5. Insert Players.
INSERT INTO "Player" ("displayName") VALUES
  ('Atraeha'),
  ('Bake'),
  ('Barbatos'),
  ('Blargn'),
  ('Bonclay'),
  ('Bored'),
  ('Boredmage'),
  ('Bugatti'),
  ('Bungle'),
  ('Byung'),
  ('Capriciousxo'),
  ('Case'),
  ('Cash'),
  ('Chainsaw'),
  ('Corr'),
  ('Creek'),
  ('Creeq'),
  ('DIsrespect'),
  ('Daladed'),
  ('Dil'),
  ('Dody'),
  ('Doge'),
  ('Dommymommy'),
  ('Doomqt'),
  ('Dumpsterbob'),
  ('Ebtmommy'),
  ('Elektro'),
  ('Elusivegod'),
  ('Fishynethers'),
  ('Girthstorm'),
  ('Glzy'),
  ('Gono'),
  ('Haanii'),
  ('Hazi'),
  ('HotforSenpai'),
  ('Jalisco'),
  ('Jestin'),
  ('Kalihiwai'),
  ('Kayotics'),
  ('Keefy'),
  ('Koco'),
  ('Lebearjames'),
  ('Lilark'),
  ('Mac'),
  ('Massesto'),
  ('Mhm'),
  ('Pizookies'),
  ('Priestlynn'),
  ('Rfx'),
  ('Sablewright'),
  ('Sergo'),
  ('Shawtydgaf'),
  ('Shmoo'),
  ('Skryt'),
  ('Sleepyrat'),
  ('Subforfeet'),
  ('Sweetmeat'),
  ('Throbby'),
  ('Tombradygoat'),
  ('Valiks'),
  ('Veile'),
  ('Viffer'),
  ('Vspades'),
  ('Whappintime'),
  ('Xenodank'),
  ('Yamz'),
  ('Yaske'),
  ('Zephleo');

-- 6. Insert Characters (playerId resolved via subquery on displayName).
INSERT INTO "Character" (name, class, spec, role, "isMain", "playerId") VALUES
  ('Bored', 'Druid', 'Feral Druid (Tank)', 'tank', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Bored')),
  ('Bungle', 'Druid', 'Restoration Druid', 'heal', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Bungle')),
  ('Capriciousxo', 'Druid', 'Balance Druid', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Capriciousxo')),
  ('Creeq', 'Druid', 'Restoration Druid', 'heal', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Creeq')),
  ('Dommymommy', 'Druid', 'Restoration Druid', 'heal', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Dommymommy')),
  ('Doomqt', 'Druid', 'Balance Druid', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Doomqt')),
  ('Fishynethers', 'Druid', 'Restoration Druid', 'heal', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Fishynethers')),
  ('Girthstorm', 'Druid', 'Feral Druid (Tank)', 'tank', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Girthstorm')),
  ('Lebearjames', 'Druid', 'Feral Druid (Tank)', 'tank', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Lebearjames')),
  ('Viffer', 'Druid', 'Restoration Druid', 'heal', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Viffer')),
  ('Byung', 'Hunter', 'Beast Mastery Hunter', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Byung')),
  ('Chainsaw', 'Hunter', 'Beast Mastery Hunter', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Chainsaw')),
  ('Glzy', 'Hunter', 'Beast Mastery Hunter', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Glzy')),
  ('Throbby', 'Hunter', 'Beast Mastery Hunter', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Throbby')),
  ('Veile', 'Hunter', 'Beast Mastery Hunter', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Veile')),
  ('Whappintime', 'Hunter', 'Beast Mastery Hunter', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Whappintime')),
  ('Blargn', 'Mage', 'Frost Mage', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Blargn')),
  ('Boredmage', 'Mage', 'Frost Mage', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Boredmage')),
  ('Hazi', 'Mage', 'Frost Mage', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Hazi')),
  ('Koco', 'Mage', 'Frost Mage', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Koco')),
  ('Lilark', 'Mage', 'Frost Mage', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Lilark')),
  ('Skryt', 'Mage', 'Frost Mage', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Skryt')),
  ('Cash', 'Paladin', 'Retribution Paladin', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Cash')),
  ('Ebtmommy', 'Paladin', 'Protection Paladin', 'tank', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Ebtmommy')),
  ('Elusivegod', 'Paladin', 'Retribution Paladin', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Elusivegod')),
  ('Kalihiwai', 'Paladin', 'Holy Paladin', 'heal', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Kalihiwai')),
  ('Keefy', 'Paladin', 'Retribution Paladin', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Keefy')),
  ('Massesto', 'Paladin', 'Protection Paladin', 'tank', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Massesto')),
  ('Sleepyrat', 'Paladin', 'Holy Paladin', 'heal', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Sleepyrat')),
  ('Subforfeet', 'Paladin', 'Holy Paladin', 'heal', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Subforfeet')),
  ('Bake', 'Priest', 'Holy Priest', 'heal', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Bake')),
  ('HotforSenpai', 'Priest', 'Holy Priest', 'heal', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'HotforSenpai')),
  ('Mac', 'Priest', 'Holy Priest', 'heal', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Mac')),
  ('Priestlynn', 'Priest', 'Shadow Priest', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Priestlynn')),
  ('Sergo', 'Priest', 'Shadow Priest', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Sergo')),
  ('Shmoo', 'Priest', 'Holy Priest', 'heal', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Shmoo')),
  ('Zephleo', 'Priest', 'Shadow Priest', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Zephleo')),
  ('Elektro', 'Rogue', 'Combat Rogue', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Elektro')),
  ('Gono', 'Rogue', 'Combat Rogue', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Gono')),
  ('Shawtydgaf', 'Rogue', 'Combat Rogue', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Shawtydgaf')),
  ('Atraeha', 'Shaman', 'Restoration Shaman', 'heal', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Atraeha')),
  ('Barbatos', 'Shaman', 'Restoration Shaman', 'heal', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Barbatos')),
  ('Bonclay', 'Shaman', 'Restoration Shaman', 'heal', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Bonclay')),
  ('Case', 'Shaman', 'Enhancement Shaman', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Case')),
  ('Creek', 'Shaman', 'Restoration Shaman', 'heal', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Creek')),
  ('Dody', 'Shaman', 'Enhancement Shaman', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Dody')),
  ('Elektro', 'Shaman', 'Elemental Shaman', 'dps', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Elektro')),
  ('Haanii', 'Shaman', 'Elemental Shaman', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Haanii')),
  ('Jestin', 'Shaman', 'Restoration Shaman', 'heal', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Jestin')),
  ('Tombradygoat', 'Shaman', 'Restoration Shaman', 'heal', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Tombradygoat')),
  ('Dil', 'Warlock', 'Affliction Warlock', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Dil')),
  ('Doge', 'Warlock', 'Affliction Warlock', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Doge')),
  ('Dumpsterbob', 'Warlock', 'Affliction Warlock', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Dumpsterbob')),
  ('Jalisco', 'Warlock', 'Affliction Warlock', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Jalisco')),
  ('Kayotics', 'Warlock', 'Affliction Warlock', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Kayotics')),
  ('Sablewright', 'Warlock', 'Affliction Warlock', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Sablewright')),
  ('Sweetmeat', 'Warlock', 'Affliction Warlock', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Sweetmeat')),
  ('Valiks', 'Warlock', 'Affliction Warlock', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Valiks')),
  ('Xenodank', 'Warlock', 'Affliction Warlock', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Xenodank')),
  ('Yamz', 'Warlock', 'Affliction Warlock', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Yamz')),
  ('Yaske', 'Warlock', 'Affliction Warlock', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Yaske')),
  ('Bugatti', 'Warrior', 'Protection Warrior', 'tank', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Bugatti')),
  ('Corr', 'Warrior', 'Fury Warrior', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Corr')),
  ('Daladed', 'Warrior', 'Fury Warrior', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Daladed')),
  ('DIsrespect', 'Warrior', 'Fury Warrior', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'DIsrespect')),
  ('Mhm', 'Warrior', 'Fury Warrior', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Mhm')),
  ('Pizookies', 'Warrior', 'Fury Warrior', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Pizookies')),
  ('Rfx', 'Warrior', 'Fury Warrior', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Rfx')),
  ('Vspades', 'Warrior', 'Fury Warrior', 'dps', TRUE, (SELECT id FROM "Player" WHERE "displayName" = 'Vspades')),
  ('Bored', 'Druid', 'Balance Druid', 'dps', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Bored')),
  ('Bugatti', 'Druid', 'Feral Druid (Tank)', 'tank', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Bugatti')),
  ('Massesto', 'Druid', 'Feral Druid (Tank)', 'tank', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Massesto')),
  ('Shawtydgaf', 'Druid', 'Feral Druid (Tank)', 'tank', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Shawtydgaf')),
  ('Skryt', 'Druid', 'Balance Druid', 'dps', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Skryt')),
  ('Zephleo', 'Druid', 'Balance Druid', 'dps', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Zephleo')),
  ('Cash', 'Hunter', 'Beast Mastery Hunter', 'dps', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Cash')),
  ('Doge', 'Hunter', 'Beast Mastery Hunter', 'dps', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Doge')),
  ('Whappintime', 'Hunter', 'Beast Mastery Hunter', 'dps', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Whappintime')),
  ('Glzy', 'Paladin', 'Retribution Paladin', 'dps', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Glzy')),
  ('Glzy', 'Paladin', 'Holy Paladin', 'heal', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Glzy')),
  ('Pizookies', 'Paladin', 'Protection Paladin', 'tank', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Pizookies')),
  ('Bake', 'Shaman', 'Restoration Shaman', 'heal', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Bake')),
  ('Corr', 'Shaman', 'Enhancement Shaman', 'dps', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Corr')),
  ('Gono', 'Shaman', 'Enhancement Shaman', 'dps', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Gono')),
  ('Keefy', 'Shaman', 'Enhancement Shaman', 'dps', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Keefy')),
  ('Rfx', 'Shaman', 'Enhancement Shaman', 'dps', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Rfx')),
  ('Skryt', 'Shaman', 'Restoration Shaman', 'heal', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Skryt')),
  ('Sleepyrat', 'Shaman', 'Enhancement Shaman', 'dps', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Sleepyrat')),
  ('Daladed', 'Warlock', 'Affliction Warlock', 'dps', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Daladed')),
  ('Koco', 'Warlock', 'Affliction Warlock', 'dps', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Koco')),
  ('Massesto', 'Warlock', 'Affliction Warlock', 'dps', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Massesto')),
  ('Vspades', 'Warlock', 'Affliction Warlock', 'dps', FALSE, (SELECT id FROM "Player" WHERE "displayName" = 'Vspades'));

-- 7. Add every Character to Master Roster as a member.
INSERT INTO "RosterMember" ("rosterId", "characterId", "memberRole")
SELECT (SELECT id FROM "Roster" WHERE name = 'Master Roster'), id, 'main' FROM "Character";

COMMIT;

-- Sanity checks (run separately):
-- SELECT COUNT(*) FROM "Player";          -- expect 68
-- SELECT COUNT(*) FROM "Character";       -- expect 92
-- SELECT COUNT(*) FROM "RosterMember";    -- expect 92