// Generate data/roster.sql from data/roster.tsv. Output is a single
// transaction safe to paste into the Neon SQL editor — applies the 0002
// migration, wipes existing roster data, then re-inserts Players /
// Characters / RosterMembers from the TSV.
//
// Usage:  tsx scripts/generate-roster-sql.ts

import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { resolve } from "node:path";
import { SPEC_BY_KEY, SPECS } from "../lib/specs";

const ROOT = resolve(__dirname, "..");
const TSV = resolve(ROOT, "data", "roster.tsv");
const OUT = resolve(ROOT, "data", "roster.sql");
const MIGRATION_NAME = "0002_drop_character_name_unique";
const MIGRATION_FILE = resolve(ROOT, "prisma", "migrations", MIGRATION_NAME, "migration.sql");

const SPEC_ALIAS: Record<string, string> = {
  "Druid:Feral (Bear)": "Feral Druid (Tank)",
  "Druid:Feral (Cat)":  "Feral Druid (DPS)",
};
const ROLE_ALIAS: Record<string, "tank" | "heal" | "dps"> = {
  "Tank":         "tank",
  "Healer":       "heal",
  "Healers":      "heal",
  "Physical DPS": "dps",
  "Caster DPS":   "dps",
  "DPS":          "dps",
};

function resolveSpecKey(className: string, specName: string): string {
  const aliasKey = `${className}:${specName}`;
  if (SPEC_ALIAS[aliasKey]) return SPEC_ALIAS[aliasKey];
  const combined = `${specName} ${className}`;
  if (SPEC_BY_KEY[combined]) return combined;
  const found = SPECS.find(
    s => s.class === className && s.key.toLowerCase().startsWith(specName.toLowerCase()),
  );
  if (found) return found.key;
  throw new Error(`No canonical spec for class="${className}" spec="${specName}"`);
}

function sqlString(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

interface Row {
  player: string;
  className: string;
  specKey: string;
  role: "tank" | "heal" | "dps";
  isMain: boolean;
}

function parseTsv(): Row[] {
  const lines = readFileSync(TSV, "utf8").split(/\r?\n/).filter(l => l.trim().length);
  const [header, ...body] = lines;
  const cols = header.split("\t").map(s => s.trim());
  const idx = (n: string) => {
    const i = cols.indexOf(n);
    if (i < 0) throw new Error(`Missing column "${n}"`);
    return i;
  };
  const iP = idx("Player"), iC = idx("Class"), iS = idx("Spec"), iR = idx("Role"), iM = idx("Main / Alt");
  return body.map((line, n) => {
    const c = line.split("\t").map(s => s.trim());
    const player = c[iP], className = c[iC], specName = c[iS], role = c[iR], mainAlt = c[iM];
    if (!player || !className || !specName || !role || !mainAlt) {
      throw new Error(`Row ${n + 2}: missing cell — "${line}"`);
    }
    const specKey = resolveSpecKey(className, specName);
    const resolvedRole = ROLE_ALIAS[role];
    if (!resolvedRole) throw new Error(`Row ${n + 2}: unknown role "${role}"`);
    if (SPEC_BY_KEY[specKey].role !== resolvedRole) {
      throw new Error(`Row ${n + 2}: role mismatch ${role} vs ${specKey}`);
    }
    return { player, className, specKey, role: resolvedRole, isMain: mainAlt.toLowerCase() === "main" };
  });
}

function build(): string {
  const rows = parseTsv();
  const players = Array.from(new Set(rows.map(r => r.player))).sort();
  const checksum = createHash("sha256").update(readFileSync(MIGRATION_FILE)).digest("hex");

  const out: string[] = [];
  out.push(`-- Generated by scripts/generate-roster-sql.ts. Do not edit by hand.`);
  out.push(`-- Source: data/roster.tsv (${rows.length} rows / ${players.length} players)`);
  out.push(`-- Paste this into Neon's SQL editor and run as a single transaction.`);
  out.push(``);
  out.push(`BEGIN;`);
  out.push(``);
  out.push(`-- 1. Apply 0002 migration: drop Character.name unique index.`);
  out.push(`DROP INDEX IF EXISTS "Character_name_key";`);
  out.push(``);
  out.push(`-- 2. Record the migration in _prisma_migrations so future deploys skip it.`);
  out.push(`INSERT INTO "_prisma_migrations" (id, checksum, finished_at, migration_name, logs, rolled_back_at, started_at, applied_steps_count)`);
  out.push(`VALUES (gen_random_uuid()::text, ${sqlString(checksum)}, NOW(), ${sqlString(MIGRATION_NAME)}, NULL, NULL, NOW(), 1)`);
  out.push(`ON CONFLICT DO NOTHING;`);
  out.push(``);
  out.push(`-- 3. Wipe existing roster data (FK-safe order).`);
  out.push(`DELETE FROM "LootAward";`);
  out.push(`DELETE FROM "Attendance";`);
  out.push(`DELETE FROM "RosterMember";`);
  out.push(`DELETE FROM "RaidNight";`);
  out.push(`DELETE FROM "Roster";`);
  out.push(`DELETE FROM "Character";`);
  out.push(`DELETE FROM "Player";`);
  out.push(``);
  out.push(`-- 4. Recreate the singleton "Master Roster".`);
  out.push(`INSERT INTO "Roster" (name, description) VALUES (${sqlString("Master Roster")}, ${sqlString("The guild roster — every active raider's character lives here.")});`);
  out.push(``);
  out.push(`-- 5. Insert Players.`);
  out.push(`INSERT INTO "Player" ("displayName") VALUES`);
  out.push(players.map(p => `  (${sqlString(p)})`).join(",\n") + `;`);
  out.push(``);
  out.push(`-- 6. Insert Characters (playerId resolved via subquery on displayName).`);
  out.push(`INSERT INTO "Character" (name, class, spec, role, "isMain", "playerId") VALUES`);
  const charRows = rows.map(r =>
    `  (${sqlString(r.player)}, ${sqlString(r.className)}, ${sqlString(r.specKey)}, ${sqlString(r.role)}, ${r.isMain ? "TRUE" : "FALSE"}, (SELECT id FROM "Player" WHERE "displayName" = ${sqlString(r.player)}))`,
  );
  out.push(charRows.join(",\n") + `;`);
  out.push(``);
  out.push(`-- 7. Add every Character to Master Roster as a member.`);
  out.push(`INSERT INTO "RosterMember" ("rosterId", "characterId", "memberRole")`);
  out.push(`SELECT (SELECT id FROM "Roster" WHERE name = ${sqlString("Master Roster")}), id, ${sqlString("main")} FROM "Character";`);
  out.push(``);
  out.push(`COMMIT;`);
  out.push(``);
  out.push(`-- Sanity checks (run separately):`);
  out.push(`-- SELECT COUNT(*) FROM "Player";          -- expect ${players.length}`);
  out.push(`-- SELECT COUNT(*) FROM "Character";       -- expect ${rows.length}`);
  out.push(`-- SELECT COUNT(*) FROM "RosterMember";    -- expect ${rows.length}`);
  return out.join("\n");
}

const sql = build();
writeFileSync(OUT, sql);
console.log(`Wrote ${OUT} (${sql.length} chars)`);
